"""Content-digested source bundle construction and verification."""

from .kernel_bundle import (
    KernelBundle,
    build_kernel_bundle,
    compute_bundle_digest,
    load_and_verify_kernel_bundle,
)
from .kernel_apply import KernelApplyReceipt, apply_verified_kernel_bundle
from .e2e_bundle import (
    E2EPatchBundle,
    build_e2e_patch_bundle,
    compute_e2e_bundle_digest,
    detect_bundle_kind,
    finalize_verified_e2e_bundle,
    load_and_verify_e2e_bundle,
    verify_replay_config_invariants,
)
from .e2e_models import (
    BuildRecipeLock,
    BuildStep,
    BundleProvenanceLock,
    DerivedImageIdentity,
    SourceComponentCapability,
    SourceFileChange,
    SourceRepositoryLock,
)
from .e2e_receipts import (
    BuiltArtifact,
    BuildStepReceipt,
    CleanReplayReceipt,
    ReplayArtifactReceipt,
    DeliveryVerificationResult,
    LoadedArtifact,
    LoadedByteEngagementReceipt,
    PrimaryVerificationEvidence,
    ReplayConfigInvariantReceipt,
    SourceBuildReceipt,
    source_stack_digest,
)
from .e2e_verify import (
    BuildAttestor,
    BundleVerifyOutcome,
    CleanReplayBackend,
    E2EBundleVerifier,
    EngagementBackend,
    EngagementRequest,
    ReplayRequest,
    SourceBuildRequest,
    SourceBuildBackend,
    SupervisedRecipeBuildBackend,
    TerminalDeliveryVerdict,
    delivery_terminal_policy,
)
from .e2e_router import (
    E2EBundleVerificationPort,
    E2EBundleVerifierRouter,
    E2EVerifierProfile,
)
from .git_patch import (
    CapturedRepositoryPatch,
    CleanPatchMaterializer,
    RepositoryApplyReceipt,
    capture_repository_patch,
    validate_lock_order,
)
from .result import TaskResult, write_task_result
from .portable_bundle import (
    PortableBundleEvidence,
    PortableBundleVerification,
    capture_portable_bundle,
    verify_portable_bundle,
)
from .reproduction import (
    e2e_reproduction_declaration,
    kernel_reproduction_declaration,
)

__all__ = [
    "BuildRecipeLock",
    "BuildStep",
    "BuildAttestor",
    "BundleProvenanceLock",
    "BuiltArtifact",
    "BuildStepReceipt",
    "BundleVerifyOutcome",
    "CapturedRepositoryPatch",
    "CleanPatchMaterializer",
    "CleanReplayReceipt",
    "ReplayArtifactReceipt",
    "CleanReplayBackend",
    "DeliveryVerificationResult",
    "DerivedImageIdentity",
    "E2EBundleVerifier",
    "E2EBundleVerificationPort",
    "E2EBundleVerifierRouter",
    "E2EVerifierProfile",
    "E2EPatchBundle",
    "EngagementRequest",
    "EngagementBackend",
    "KernelBundle",
    "KernelApplyReceipt",
    "LoadedArtifact",
    "LoadedByteEngagementReceipt",
    "PrimaryVerificationEvidence",
    "PortableBundleEvidence",
    "PortableBundleVerification",
    "ReplayConfigInvariantReceipt",
    "ReplayRequest",
    "RepositoryApplyReceipt",
    "SourceBuildReceipt",
    "SourceBuildBackend",
    "SourceBuildRequest",
    "SourceComponentCapability",
    "SourceFileChange",
    "SourceRepositoryLock",
    "SupervisedRecipeBuildBackend",
    "TaskResult",
    "TerminalDeliveryVerdict",
    "build_e2e_patch_bundle",
    "build_kernel_bundle",
    "apply_verified_kernel_bundle",
    "capture_repository_patch",
    "capture_portable_bundle",
    "compute_e2e_bundle_digest",
    "compute_bundle_digest",
    "detect_bundle_kind",
    "delivery_terminal_policy",
    "e2e_reproduction_declaration",
    "finalize_verified_e2e_bundle",
    "load_and_verify_e2e_bundle",
    "load_and_verify_kernel_bundle",
    "kernel_reproduction_declaration",
    "source_stack_digest",
    "verify_replay_config_invariants",
    "verify_portable_bundle",
    "validate_lock_order",
    "write_task_result",
]
