"""Runtime dependency bootstrap and process-environment boundaries."""

from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORT_MODULES = {
    "BootstrapError": "repositories",
    "DependencyBootstrapper": "dependencies",
    "DependencyLock": "dependencies",
    "LockedDependency": "dependencies",
    "PythonEnvironment": "dependencies",
    "PythonProbe": "dependencies",
    "RepositoryResolver": "repositories",
    "RepositoryState": "repositories",
    "ResolvedRepository": "repositories",
    "canonical_repository": "repositories",
    "inspect_repository": "repositories",
    "load_lock": "dependencies",
    "probe_errors": "dependencies",
    "version_matches": "dependencies",
    "CorpusFile": "magpie_corpus",
    "MagpieCorpusManifest": "magpie_corpus",
    "build_magpie_corpus_manifest": "magpie_corpus",
    "load_magpie_corpus_manifest": "magpie_corpus",
    "verify_magpie_corpus_manifest": "magpie_corpus",
    "MagpieCompatibilityEntry": "magpie_compatibility",
    "MagpieCompatibilityLedger": "magpie_compatibility",
    "MagpieConfigContract": "magpie_config",
    "MagpieMainConfigAdapter": "magpie_config",
    "MagpieMainPublicApi": "magpie_main",
    "validate_apex_magpie_config_documents": "magpie_config",
    "build_magpie_compatibility_ledger": "magpie_compatibility",
    "load_magpie_compatibility_ledger": "magpie_compatibility",
    "verify_magpie_compatibility_ledger": "magpie_compatibility",
    "DependencyReceipt": "receipt",
    "verify_runtime_dependencies": "receipt",
    "DownloadLock": "lm_eval_lock",
    "LmEvalRuntimeLock": "lm_eval_lock",
    "EvaluatorDatasetLockFile": "evaluator_lock",
    "EvaluatorPolicyLock": "evaluator_lock",
    "load_evaluator_policy_lock": "evaluator_lock",
    "WheelLock": "lm_eval_lock",
    "load_lm_eval_runtime_lock": "lm_eval_lock",
    "LmEvalRuntimeReceipt": "lm_eval_runtime",
    "default_lm_eval_runtime_root": "lm_eval_runtime",
    "verify_lm_eval_runtime": "lm_eval_runtime",
    "LmEvalRuntimePreparer": "lm_eval_prepare",
    "SourceCheckoutReceipt": "source_locks",
    "SourceLockManager": "source_locks",
    "SourceLockReceipt": "source_locks",
    "SourceLockSet": "source_locks",
    "SourceLockSpec": "source_locks",
    "default_source_checkout_root": "source_locks",
    "default_source_lock_path": "source_locks",
    "default_source_roots": "source_locks",
    "load_source_lock": "source_locks",
    "ComponentSourceLockSet": "provenance",
    "ContainerIdentity": "provenance",
    "ProvenanceResolver": "provenance",
    "RepositoryLock": "provenance",
    "RunProvenance": "provenance",
    "GpuLease": "gpu",
    "GpuLeaseManager": "gpu",
    "GpuLeaseReceipt": "gpu",
    "LocalGpuLease": "gpu",
    "LocalGpuLeaseManager": "gpu",
    "resolve_gpu_device_scope": "gpu",
    "GpuLeaseHeartbeatReceipt": "gpu_lifecycle",
    "GpuLeaseOwnerIdentity": "gpu_lifecycle",
    "GpuMeasurementBracketReceipt": "gpu_lifecycle",
    "GpuMeasurementGuard": "gpu_lifecycle",
    "require_gpu_measurement_guard": "gpu_lifecycle",
    "require_gpu_lease_heartbeat": "gpu_lifecycle",
    "GpuDeviceIdentity": "gpu_topology",
    "GpuSelectorRequest": "gpu_topology",
    "RsmiDeviceIdentity": "gpu_topology",
    "CleanHsaInventoryProvider": "hsa_inventory",
    "HsaGpuIdentity": "hsa_inventory",
    "HsaInventoryEvidence": "hsa_inventory",
    "GpuOwnershipInspector": "gpu_ownership",
    "GpuOwnershipReceipt": "gpu_ownership",
    "GpuProcessIdentity": "gpu_ownership",
    "RocmSmiGpuOwnershipInspector": "gpu_ownership",
    "collect_gpu_ownership": "gpu_ownership",
    "GpuDoctorInspector": "gpu_doctor",
    "GpuDoctorReceipt": "gpu_doctor",
    "GpuProcessContext": "gpu_doctor",
    "LinuxGpuDoctorInspector": "gpu_doctor",
    "load_gpu_doctor_receipt": "gpu_doctor_load",
    "CtypesRocmHealthInspector": "gpu_health",
    "RocmHealthApi": "gpu_health",
    "RocmHealthDevice": "gpu_health",
    "RocmHealthInspector": "gpu_health",
    "RocmHealthReceipt": "gpu_health",
    "collect_rocm_health": "gpu_health",
    "WorkspaceGitIdentityResolver": "workspace_identity",
    "FormalResultsRootValidator": "formal_results",
    "formal_results_validator": "formal_results",
    "EvaluatorQualificationArtifactAuthority": "qualification_artifacts",
    "QualificationArtifactCollection": "qualification_artifacts",
    "QualificationArtifactResolution": "qualification_artifacts",
    "QualificationArtifactSet": "qualification_artifacts",
    "QualificationCampaignArtifactVerifier": "qualification_artifacts",
    "ReadOnlyQualificationArtifactStore": "qualification_artifacts",
    "LocalReleaseEvidenceCollector": "release_collection",
    "collect_local_release_evidence": "release_collection",
    "BaselineAuditEvidence": "release_evidence",
    "CliIdentityEvidence": "release_evidence",
    "CpuGateEvidence": "release_evidence",
    "DependencyVerificationEvidence": "release_evidence",
    "ImageIdentityEvidence": "release_evidence",
    "MagpieConfigResolutionEntryEvidence": "release_evidence",
    "MagpieConfigResolutionEvidence": "release_evidence",
    "QUALIFICATION_IDS": "release_qualification",
    "QualificationEvidence": "release_qualification",
    "build_qualification_evidence": "release_qualification",
    "ReleaseEvidence": "release_evidence",
    "ShowcaseEvidence": "release_showcase",
    "build_showcase_evidence": "release_showcase",
    "VerifiedComponentEvidence": "release_evidence",
    "build_magpie_config_resolution_evidence": "release_evidence",
    "ReleaseCandidateReceipt": "release_candidate",
    "freeze_campaign_baseline": "release_candidate",
    "freeze_release_candidate": "release_candidate",
    "inspect_release_candidate": "release_candidate",
    "verify_release_candidate_receipt": "release_candidate",
}


def __getattr__(name: str) -> Any:
    """Lazily expose the public API without preloading executable modules."""

    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(f"{__name__}.{module_name}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = sorted(_EXPORT_MODULES)
