apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keystone

resources:
  - ../namespace.yaml
  - ../base/pvc.yaml
  - ../base/mcp-deployment.yaml
  - optimizer-job.yaml

commonLabels:
  app.kubernetes.io/part-of: keystone
  app.kubernetes.io/component: workload-optimizer
